### ISSUE TITLE
Ressource missing - No such token 

### ISSUE THREAD

**Issue by progz** [simalexan/twitch-payments-service#1]
Hi, 
First thanks for the code and for the youtube video, it was very well explained and useful.

I pull your code and try it on lambda but when I submit the form, ApiGateway respond me with an error : 
>{
"type": "StripeInvalidRequestError",
"stack": "Error: No such token: tok_1CfOqf2eZvKYlo2C8buOFsI4\n    at Constructor._Error (/var/task/node_modules/stripe/lib/Error.js:12:17)\n    at Constructor (/var/task/node_modules/stripe/lib/utils.js:133:13)\n    at new Constructor (/var/task/node_modules/stripe/lib/utils.js:133:13)\n    at Function.StripeError.generate (/var/task/node_modules/stripe/lib/Error.js:57:12)\n    at IncomingMessage.<anonymous> (/var/task/node_modules/stripe/lib/StripeResource.js:170:39)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)",
"rawType": "invalid_request_error",
"code": "resource_missing",
"param": "source",
"message": "No such token: tok_1CfOqf2eZvKYlo2C8buOFsI4",
"raw": {
"code": "resource_missing",
"doc_url": "https://stripe.com/docs/error-codes/resource-missing",
"message": "No such token: tok_1CfOqf2eZvKYlo2C8buOFsI4",
"param": "source",
"type": "invalid_request_error",
"headers": {
"server": "nginx",
"date": "Thu, 21 Jun 2018 09:13:05 GMT",
"content-type": "application/json",
"content-length": "245",
"connection": "close",
"access-control-allow-credentials": "true",
"access-control-allow-methods": "GET, POST, HEAD, OPTIONS, DELETE",
"access-control-allow-origin": "*",
"access-control-expose-headers": "Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required",
"access-control-max-age": "300",
"cache-control": "no-cache, no-store",
"request-id": "req_Zupq5ZfIGvkeY9",
"stripe-version": "2018-05-21"
},
"statusCode": 400,
"requestId": "req_Zupq5ZfIGvkeY9"
},
"headers": {
"server": "nginx",
"date": "Thu, 21 Jun 2018 09:13:05 GMT",
"content-type": "application/json",
"content-length": "245",
"connection": "close",
"access-control-allow-credentials": "true",
"access-control-allow-methods": "GET, POST, HEAD, OPTIONS, DELETE",
"access-control-allow-origin": "*",
"access-control-expose-headers": "Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required",
"access-control-max-age": "300",
"cache-control": "no-cache, no-store",
"request-id": "req_Zupq5ZfIGvkeY9",
"stripe-version": "2018-05-21"
},
"requestId": "req_Zupq5ZfIGvkeY9",
"statusCode": 400
}

FYI, I use the last version of Stripe (6.1.1) but when I check the documentation there is no change... [https://stripe.com/docs/charges](https://stripe.com/docs/charges)

If you have an idea, thanks a lot.

**Comment by progz** [comment]
Sorry for this issue !
Everything is working !

I was not using the good pub/secret key pair...
